# -*- coding: utf-8 -*-
"""sample_dfs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139GW7Ny75sCrQ6u6Lm1D2dPQg0JfjsMd
"""

import seaborn as sns
import pandas as pd
import numpy as np

tips = sns.load_dataset("tips")

df_1 = tips.copy()
df_1 = df_1['total_bill tip size'.split()]
df_1.head()

df_2 = tips.copy()
df_2 = df_2['total_bill size day time'.split()]
df_2.head()

for col in df_1:
    vals_to_nan = df_1[col].sample(frac=.10).index
    df_1.loc[vals_to_nan, col] = np.NaN